# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 阿悟的小破栈 - 阿悟的小破博客
description: 阿悟的小破博客
keywords: 体育特长生,沉淀,大厂保洁,Java,backend,后端,大厂程序员
author: 悟Wuuuu
language: en
favicon: /img/category.jpg
medium_zoom: true

subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # loop (循環打字)
  loop: true
  sub:
    - 雄关漫道真如铁
    - 而今迈步从头越

# 加载动画 Loading Animation
preloader:
  enable: true
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  source: 1
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url: https://github.com/dengWuuu/dengWuuu.github.io/blob/main/source/css/center-atom.css

# Snackbar 弹窗
# https://github.com/polonel/SnackBar
# position 弹窗位置
# 可选 top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: true
  position: bottom-left
  bg_light: '#49b1f5' #light mode时弹窗背景
  bg_dark: '#2d3035' #dark mode时弹窗背景

footer_bg: true
chat_btn: true

background: https://github.com/dengWuuu/dengWuuu.github.io/blob/main/source/img/background.jpg

index_img: /img/background.jpg
avatar:
  img: /img/preview.gif
# If the banner of page not setting, it will show the top_img
default_top_img: /img/background.jpg

# The banner image of archive page
archive_img: /img/background.jpg

# If the banner of tag page not setting, it will show the top_img
# note: tag page, not tags page (子標籤頁面的 top_img)
tag_img: /img/tag.jpg

# The banner image of tag page
# format:
#  - tag name: xxxxx
tag_per_img: /img/tag.jpg

# If the banner of category page not setting, it will show the top_img
# note: category page, not categories page (子分類頁面的 top_img)
category_img: /img/category.jpg

# The banner image of category page
# format:
#  - category name: xxxxx
category_per_img: /img/category.jpg


display_mode: dark

darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: true
  # Switch dark/light mode automatically (自動切換 dark mode和 light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: false

beautify:
  enable: true
  field: post # site/post
  title-prefix-icon: # '\f0c1'
  title-prefix-icon-color: # '#F47466'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://dengwuuu.github.io/
permalink: post/:abbrlink.html # post为自定义前缀
abbrlink:
  alg: crc32   #算法： crc16(default) and crc32
  rep: hex     #进制： dec(default) and hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

post_meta:
  page:
    date_type: both # created or updated or both 主页文章日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 主页是否显示分类
    tags: true # true or false 主页是否显示标签
    label: true # true or false 显示描述性文字
  post:
    date_type: both # created or updated or both 文章页日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 文章页是否显示分类
    tags: true # true or false 文章页是否显示标签
    label: true # true or false 显示描述性文字


作者: Jerry
連結: https://butterfly.js.org/posts/4aa8abbe/#%E6%96%87%E7%AB%A0%E5%B0%81%E9%9D%A2
來源: Butterfly
  著作權歸作者所有。商業轉載請聯繫作者獲得授權，非商業轉載請註明出處。

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/dengWuuu/dengWuuu.github.io.git
  branch: main
  message: update blog

highlight_copy: true


canvas_fluttering_ribbon:
  enable: true
  mobile: true # false 手机端不显示 true 手机端显示


# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖動特效)
  mobile: false


fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

aside:
  enable: true
  hide: false
  button: true
  mobile: false # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description: 要好好学学了
    button:
      enable: true
      icon: iconfont icon-youxishoubing
      text: 摸鱼
      link: https://dengwuuu.github.io/
  card_announcement:
    enable: true
    content:
      <p align="center"><b><font color="#e66b6d">雄</font><font color="#e66d98">关</font><font color="#e66cc6">漫</font><font color="#cc6de6">道</font><font color="#9770e6">真</font><font color="#6d93e6">如</font><font color="#6fcde6">铁</font></b></p>
      <p align="center">微信号：wdw330327</p>
      <p align="center">QQ号：1076766987</p>
      <p align="center">Github：https://github.com/dengWuuu</p>
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works
  card_tags color: true

newest_comments:
  enable: true
  sort_order: # Don't modify the setting unless you know how it works
  limit: 6
  storage: 10 # unit: mins, save data to localStorage
  avatar: true

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

readmode: true

runtimeshow:
  enable: true
  publish_date: 6/7/2021 00:00:00
  ##网页开通时间
  #格式: 月/日/年 时间
  #也可以写成 年/月/日 时间

# electric_clock
# see https://akilar.top/posts/4e39cf4a/
electric_clock:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  exclude:
    - /posts/
    - /about/
  layout: # 挂载容器类型
    type: class
    name: sticky_layout
    index: 0
  loading: https://npm.elemecdn.com/hexo-butterfly-clock/lib/loading.gif #加载动画自定义
  clock_css: https://npm.elemecdn.com/hexo-butterfly-clock/lib/clock.min.css
  clock_js: https://npm.elemecdn.com/hexo-butterfly-clock/lib/clock.min.js
  ip_api: https://pv.sohu.com/cityjson?ie=utf-8


wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

inject:
  head:
    - <link rel="stylesheet" href="/css/universe.css">
  bottom:
    - <canvas id="universe"></canvas>
    - <script defer src="/js/universe.js"></script>
    - <script src="/js/sun_moon.js" async></script>
# A simple 404 page
error_404:
  enable: true
  subtitle: "頁面沒有找到"
  background: /img/404.jpg

menu:
  首頁: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友情链接: /link/ || fas fa-link
  关于博主: /about/ || fas fa-heart

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: Gitalk
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page

# 搜索功能相关配置
local_search:
  enable: true
  preload: false
  CDN:



# Post edit
# Easily browse and edit blog source code online.
post_edit:
  enable: true
  # url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name/
  # For example: https://github.com/jerryc127/butterfly.js.org/edit/main/source/
  url: https://github.com/dengWuuu/dengWuuu.github.io



gitalk:
  client_id: 8d0773b4af3628fec1f7
  client_secret: 6910ee95c2b1e4610201196cb713529bd9ac2428
  repo: comment
  owner: dengWuuu
  admin: dengWuuu
  createIssueManually: true



index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config

related_post:
  enable: true
  limit: 6 # 显示推荐文章数目
  date_type: created # or created or updated 文章日期显示创建日或者更新日

# 插入图片设置
marked:
  prependRoot: true
  postAsset: true